### ISSUE TITLE
RuntimeError - Failed to download pods to merge

### ISSUE THREAD

**Issue by swiatrzyk** [grab/cocoapods-pod-merge#21]
Hi, for some reason I cannot setup the plugin.
Here's my Gemfile:
```
source "https://rubygems.org"

gem "fastlane"
gem 'cocoapods'
gem 'cocoapods-pod-merge'
```
After this I've called `bundle install` then  `bundle exec pod install`
When I add `plugin 'cocoapods-pod-merge'` to my Podfile I get error:
```
RuntimeError - Failed to download pods to merge
/Library/Ruby/Gems/2.6.0/gems/cocoapods-pod-merge-0.0.4/lib/cocoapods-pod-merge/Main.rb:223:in `block in merge'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-pod-merge-0.0.4/lib/cocoapods-pod-merge/Main.rb:222:in `chdir'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-pod-merge-0.0.4/lib/cocoapods-pod-merge/Main.rb:222:in `merge'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-pod-merge-0.0.4/lib/cocoapods-pod-merge/Main.rb:68:in `block in begin'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-pod-merge-0.0.4/lib/cocoapods-pod-merge/Main.rb:67:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-pod-merge-0.0.4/lib/cocoapods-pod-merge/Main.rb:67:in `begin'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-pod-merge-0.0.4/lib/cocoapods_plugin.rb:8:in `block in <module:CocoapodsPodMerge>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:115:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/hooks_manager.rb:114:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:599:in `run_plugins_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:220:in `block in prepare'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:216:in `prepare'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:155:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

```

**Comment by biocross** [comment]
@swiatrzyk From the error, looks like it's failing to download one of the Pods mentioned in the `MergeFile`. Is it possible for you to share your `MergeFile`?
